import { readFile, writeFile } from 'node:fs/promises';

const root = new URL('../', import.meta.url);
const entries = [
  { path: 'src/games/1math3/core.js', imports: 0, exports: ['GAME', 'enumerateCandidates', 'buildSession', 'publicQuestion', 'normalizeNumber', 'evaluateStep', 'skipQuestion', 'summarize', 'questionExplanation'] },
  { path: 'src/services/mock-game-service.js', imports: 1, exports: ['GameService', 'MockGameService'] },
  { path: 'src/services/firebase-game-service.js', imports: 2, exports: ['FirebaseGameService'] },
  { path: 'src/student/app.js', imports: 3, exports: [] },
];

async function build() {
  const parts = [];
  for (const entry of entries) {
    const source = await readFile(new URL(entry.path, root), 'utf8');
    let imports = 0;
    let exports = 0;
    const body = source
      .replace(/^import \{[^\n]+\} from '[^']+';\r?\n/gm, () => { imports++; return ''; })
      .replace(/^export (?=(?:const|function|class) )/gm, () => { exports++; return ''; });
    if (imports !== entry.imports || exports !== entry.exports.length || /^(?:import|export)\s/m.test(body)) {
      throw new Error(`${entry.path}: unexpected module syntax; update the browser build step`);
    }
    parts.push(`// ${entry.path}\n${body.trimEnd()}`);
  }
  return `// Generated by node tools/build-1math3.mjs. Edit source modules instead.\n(() => {\n'use strict';\n\nconst core = (() => {\n${parts[0]}\nreturn { ${entries[0].exports.join(', ')} };\n})();\n\nconst services = (({ GAME, buildSession, evaluateStep, skipQuestion, summarize }) => {\n${parts[1]}\nreturn { ${entries[1].exports.join(', ')} };\n})(core);\n\nconst firebaseService = (({ GAME }, { GameService, MockGameService }) => {\n${parts[2]}\nreturn { FirebaseGameService };\n})(core, services);\n\n(({ GAME, questionExplanation, summarize }, { MockGameService }, { FirebaseGameService }) => {\n${parts[3]}\n})(core, services, firebaseService);\n})();\n`;
}

const outputUrl = new URL('src/student/1math3.bundle.js', root);
const output = await build();
if (process.argv.includes('--check')) {
  const current = await readFile(outputUrl, 'utf8').catch(() => '');
  if (current !== output) {
    console.error('Browser bundle is out of date. Run: node tools/build-1math3.mjs');
    process.exitCode = 1;
  } else console.log('Browser bundle is current.');
} else {
  await writeFile(outputUrl, output);
  console.log('Built src/student/1math3.bundle.js');
}
